<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The features that the network trains on
### Hidden Layer: Intermediary calculated features that are blackbox
### Output Layer: The prediction, the final output
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
# Global imports
import pandas as pd
import numpy as np

In [2]:

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [4]:
##### Your Code Here #####
# Define Sigmoid activation function and it's derivative for updating weights
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx / (1 - sx)

In [11]:
# Initialize random weight for each input (2 in this case)
np.random.seed(42)
weights = np.random.random((2,1))
weights

array([[0.37454012],
       [0.95071431]])

In [12]:
# Calculate Weighted Sum of inputs and weights
inputs = df[['x1', 'x2']].to_numpy()
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.        ],
       [0.37454012],
       [0.95071431],
       [1.32525443]])

In [13]:
inputs

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [14]:
# Output activated value (first iteration of predictions)
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.59255557],
       [0.72125881],
       [0.79005458]])

In [16]:
# Take difference of output and true values to calculate error
correct_output = df[['y']].to_numpy()
error = correct_output - activated_output
error

array([[ 0.5       ],
       [ 0.40744443],
       [ 0.27874119],
       [-0.79005458]])

In [17]:
correct_output

array([[1],
       [1],
       [1],
       [0]])

In [9]:
# Backpropogation - Adjust the weights to minimize error
# Gradient Descent - Use the derivative to find the minimum of a function (find min error)

adjustments = error * sigmoid_derivative(activated_output)
adjustments

array([[ 0.82436064],
       [ 0.73690584],
       [ 0.57337648],
       [-1.74089844]])

In [10]:
# At this point we have an untrained perceptron
# 1. We've randomly initialized some weights ('weights')
# 2. We have features and targets ('inputs', 'correct_output')

# Now, Update the weights n times, which should reduce the error
num_iterations = 10000
for iteration in range(num_iterations):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)

    # Activate
    activated_output = sigmoid(weighted_sum)

    # Calculate the error
    error = correct_output - activated_output

    # Make adjustments informed by the error
    adjustments = error * sigmoid_derivative(activated_output)

    # Update the weights
    weights += np.dot(inputs.T, adjustments)

print("Weights after training: \n", weights)
print("Output after training: \n", activated_output)
print("Error after training: \n", correct_output - activated_output)


Weights after training: 
 [[-3.33066907e-16]
 [ 1.27675648e-15]]
Output after training: 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
Error after training: 
 [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [10]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?